In [ ]:
import xarray as xr
import matplotlib.pyplot as plt

# Open the NetCDF file and load the data
path= "/jet/home/ding0928/python_analysis/Han_connect/nc_flie/u-ct706/full_nc_files/"
filename = path+'Rgn_number_of_particles_per_air_molecule_of_soluble_nucleation_mode_aerosol_in_air_m01s34i101.nc'
ds = xr.open_dataset(filename)

# Extract the variable and time data from the dataset
variable_data = ds['number_of_particles_per_air_molecule_of_soluble_nucleation_mode_aerosol_in_air'].values
time_data = ds['time'].values

# Convert the time data to a pandas datetime object
time_units = ds['time'].attrs['units']
time_calendar = ds['time'].calendar
time = xr.coding.times.decode_cf_datetime(time_data, units=time_units, calendar=time_calendar)

# Create a linear plot of the variable against time
plt.plot(time, variable_data)
plt.xlabel('Time')
plt.ylabel('Variable')
plt.title('Linear Plot of Variable against Time')
plt.show()

In [1]:
import xarray as xr
import matplotlib.pyplot as plt

# Open the NetCDF file and load the data
path= "/jet/home/ding0928/python_analysis/Han_connect/nc_flie/u-ct706/full_nc_files/"
filename = path+'Rgn_number_of_particles_per_air_molecule_of_soluble_nucleation_mode_aerosol_in_air_m01s34i101.nc'
ds = xr.open_dataset(filename)

In [3]:
# Extract the variable and time data from the dataset
variable_data = ds['number_of_particles_per_air_molecule_of_soluble_nucleation_mode_aerosol_in_air'].values
time_data = ds['time'].values
print(time_data)
print(ds['time'].attrs)
print(ds['time'].attrs['time'])
# Convert the time data to a pandas datetime object
time_units = ds['time'].attrs['units']
time_calendar = ds['time'].calendar
time = xr.coding.times.decode_cf_datetime(time_data, units=time_units, calendar=time_calendar)

['2014-07-20T01:00:00.000000000' '2014-07-20T04:00:00.000000000'
 '2014-07-20T07:00:00.000000000' '2014-07-20T10:00:00.000000000'
 '2014-07-20T13:00:00.000000000' '2014-07-20T16:00:00.000000000'
 '2014-07-20T19:00:00.000000000' '2014-07-20T22:00:00.000000000'
 '2014-07-21T01:00:00.000000000' '2014-07-21T04:00:00.000000000'
 '2014-07-21T07:00:00.000000000' '2014-07-21T10:00:00.000000000'
 '2014-07-21T13:00:00.000000000' '2014-07-21T16:00:00.000000000'
 '2014-07-21T19:00:00.000000000' '2014-07-21T22:00:00.000000000'
 '2014-07-22T01:00:00.000000000' '2014-07-22T04:00:00.000000000'
 '2014-07-22T07:00:00.000000000' '2014-07-22T10:00:00.000000000'
 '2014-07-22T13:00:00.000000000' '2014-07-22T16:00:00.000000000'
 '2014-07-22T19:00:00.000000000' '2014-07-22T22:00:00.000000000'
 '2014-07-23T01:00:00.000000000' '2014-07-23T04:00:00.000000000'
 '2014-07-23T07:00:00.000000000' '2014-07-23T10:00:00.000000000'
 '2014-07-23T13:00:00.000000000' '2014-07-23T16:00:00.000000000'
 '2014-07-23T19:00:00.000000000' '2014-07-23T22:00:00.000000000'
 '2014-07-24T01:00:00.000000000' '2014-07-24T04:00:00.000000000'
 '2014-07-24T07:00:00.000000000' '2014-07-24T10:00:00.000000000'
 '2014-07-24T13:00:00.000000000' '2014-07-24T16:00:00.000000000'
 '2014-07-24T19:00:00.000000000' '2014-07-24T22:00:00.000000000'
 '2014-07-25T01:00:00.000000000' '2014-07-25T04:00:00.000000000'
 '2014-07-25T07:00:00.000000000' '2014-07-25T10:00:00.000000000'
 '2014-07-25T13:00:00.000000000' '2014-07-25T16:00:00.000000000'
 '2014-07-25T19:00:00.000000000' '2014-07-25T22:00:00.000000000'
 '2014-07-26T01:00:00.000000000' '2014-07-26T04:00:00.000000000'
 '2014-07-26T07:00:00.000000000' '2014-07-26T10:00:00.000000000'
 '2014-07-26T13:00:00.000000000' '2014-07-26T16:00:00.000000000'
 '2014-07-26T19:00:00.000000000' '2014-07-26T22:00:00.000000000'
 '2014-07-27T01:00:00.000000000' '2014-07-27T04:00:00.000000000'
 '2014-07-27T07:00:00.000000000' '2014-07-27T10:00:00.000000000'
 '2014-07-27T13:00:00.000000000' '2014-07-27T16:00:00.000000000'
 '2014-07-27T19:00:00.000000000' '2014-07-27T22:00:00.000000000'
 '2014-07-28T01:00:00.000000000' '2014-07-28T04:00:00.000000000'
 '2014-07-28T07:00:00.000000000' '2014-07-28T10:00:00.000000000'
 '2014-07-28T13:00:00.000000000' '2014-07-28T16:00:00.000000000'
 '2014-07-28T19:00:00.000000000' '2014-07-28T22:00:00.000000000'
 '2014-07-29T01:00:00.000000000' '2014-07-29T04:00:00.000000000'
 '2014-07-29T07:00:00.000000000' '2014-07-29T10:00:00.000000000'
 '2014-07-29T13:00:00.000000000' '2014-07-29T16:00:00.000000000'
 '2014-07-29T19:00:00.000000000' '2014-07-29T22:00:00.000000000'
 '2014-07-30T01:00:00.000000000' '2014-07-30T04:00:00.000000000'
 '2014-07-30T07:00:00.000000000' '2014-07-30T10:00:00.000000000'
 '2014-07-30T13:00:00.000000000' '2014-07-30T16:00:00.000000000'
 '2014-07-30T19:00:00.000000000' '2014-07-30T22:00:00.000000000'
 '2014-07-31T01:00:00.000000000' '2014-07-31T04:00:00.000000000'
 '2014-07-31T07:00:00.000000000' '2014-07-31T10:00:00.000000000'
 '2014-07-31T13:00:00.000000000' '2014-07-31T16:00:00.000000000'
 '2014-07-31T19:00:00.000000000' '2014-07-31T22:00:00.000000000'
 '2014-08-01T01:00:00.000000000' '2014-08-01T04:00:00.000000000'
 '2014-08-01T07:00:00.000000000' '2014-08-01T10:00:00.000000000'
 '2014-08-01T13:00:00.000000000' '2014-08-01T16:00:00.000000000'
 '2014-08-01T19:00:00.000000000' '2014-08-01T22:00:00.000000000'
 '2014-08-02T01:00:00.000000000' '2014-08-02T04:00:00.000000000'
 '2014-08-02T07:00:00.000000000' '2014-08-02T10:00:00.000000000'
 '2014-08-02T13:00:00.000000000' '2014-08-02T16:00:00.000000000'
 '2014-08-02T19:00:00.000000000' '2014-08-02T22:00:00.000000000'
 '2014-08-03T01:00:00.000000000' '2014-08-03T04:00:00.000000000'
 '2014-08-03T07:00:00.000000000' '2014-08-03T10:00:00.000000000'
 '2014-08-03T13:00:00.000000000' '2014-08-03T16:00:00.000000000'
 '2014-08-03T19:00:00.000000000' '2014-08-03T22:00:00.000000000'
 '2014-08-04T01:00:00.000000000' '2014-08-04T04:00:00.000000000'
 '2014-08-04T07:00:00.000000000' '2014-08-04T10:00:00.000000000'
 '2014-08-04T13:00:00.000000000' '2014-08-04T16:00:00.000000000'
 '2014-08-04T19:00:00.000000000' '2014-08-04T22:00:00.000000000'
 '2014-08-05T01:00:00.000000000' '2014-08-05T04:00:00.000000000'
 '2014-08-05T07:00:00.000000000' '2014-08-05T10:00:00.000000000'
 '2014-08-05T13:00:00.000000000' '2014-08-05T16:00:00.000000000'
 '2014-08-05T19:00:00.000000000' '2014-08-05T22:00:00.000000000'
 '2014-08-06T01:00:00.000000000' '2014-08-06T04:00:00.000000000'
 '2014-08-06T07:00:00.000000000' '2014-08-06T10:00:00.000000000'
 '2014-08-06T13:00:00.000000000' '2014-08-06T16:00:00.000000000'
 '2014-08-06T19:00:00.000000000' '2014-08-06T22:00:00.000000000'
 '2014-08-07T01:00:00.000000000' '2014-08-07T04:00:00.000000000'
 '2014-08-07T07:00:00.000000000' '2014-08-07T10:00:00.000000000'
 '2014-08-07T13:00:00.000000000' '2014-08-07T16:00:00.000000000'
 '2014-08-07T19:00:00.000000000' '2014-08-07T22:00:00.000000000'
 '2014-08-08T01:00:00.000000000' '2014-08-08T04:00:00.000000000'
 '2014-08-08T07:00:00.000000000' '2014-08-08T10:00:00.000000000'
 '2014-08-08T13:00:00.000000000' '2014-08-08T16:00:00.000000000'
 '2014-08-08T19:00:00.000000000' '2014-08-08T22:00:00.000000000'
 '2014-08-09T01:00:00.000000000' '2014-08-09T04:00:00.000000000'
 '2014-08-09T07:00:00.000000000' '2014-08-09T10:00:00.000000000'
 '2014-08-09T13:00:00.000000000' '2014-08-09T16:00:00.000000000'
 '2014-08-09T19:00:00.000000000' '2014-08-09T22:00:00.000000000'
 '2014-08-10T01:00:00.000000000' '2014-08-10T04:00:00.000000000'
 '2014-08-10T07:00:00.000000000' '2014-08-10T10:00:00.000000000'
 '2014-08-10T13:00:00.000000000' '2014-08-10T16:00:00.000000000'
 '2014-08-10T19:00:00.000000000' '2014-08-10T22:00:00.000000000'
 '2014-08-11T01:00:00.000000000' '2014-08-11T04:00:00.000000000'
 '2014-08-11T07:00:00.000000000' '2014-08-11T10:00:00.000000000']
{'axis': 'T', 'standard_name': 'time'}

KeyError: 'units'

In [ ]:
# Create a linear plot of the variable against time
plt.plot(time, variable_data)
plt.xlabel('Time')
plt.ylabel('Variable')
plt.title('Linear Plot of Variable against Time')
plt.show()